- id: check-multiline-docstrings
  name: Multi-line docstring checker
  description: Check whether multi-line docstrings start and end with a single newline character
  entry: check-multiline-docstrings
  language: python
  types: [python]

- id: check-module-docstring-space
  name: Module docstring space checker
  description: Check whether module docstrings start and end with a single newline character
  entry: check-module-docstring-spaces
  language: python
  types: [python]
